"""Configuration package: runtime settings + analytics thresholds + logging."""

from .algorithms import (
    ANALYSIS_DEFAULTS,
    ANALYTICS_CONFIG,
    BOARD_HIDE_OBSOLETE,
    BOARD_MIN_RECENT_VIEW,
    CATCHUP_EMOJI,
    CATCHUP_LABELS,
    CATCHUP_THRESHOLDS,
    HOME_FILTERS,
    HOME_FILTER_LABELS,
    HOTNESS_REFERENCE,
    HOTNESS_WEIGHTS,
    GROWTH_SCORE_FULL,
    GROWTH_SCORE_ZERO,
    LIFECYCLE_EMOJI,
    LIFECYCLE_LABELS,
    LIFECYCLE_STAGES,
    LIFECYCLE_THRESHOLDS,
    LOW_SAMPLE_DAMPING,
    MIN_GROWTH_DISCUSSION,
    MIN_SAMPLE_VIDEOS,
    RELEVANCE_THRESHOLD,
    RELEVANCE_WEIGHTS,
    STRONG_ALIAS_LEN,
)
from .logging import configure_logging, get_logger
from .settings import BACKEND_DIR, ENV_FILE, PROJECT_DIR, Settings, get_settings, settings
from .taxonomy import (
    COLLECTION_KEYS,
    COLLECTIONS,
    FALLBACK_TAG,
    MAX_TAGS_PER_MEME,
    MEME_TAGS,
    TAG_EMOJI,
    TAG_HINTS,
    TAG_KEYS,
    TAG_LABELS,
    YEARLY_TOP_N,
    CollectionSpec,
    TagSpec,
)

__all__ = [
    "Settings",
    "get_settings",
    "settings",
    "BACKEND_DIR",
    "PROJECT_DIR",
    "ENV_FILE",
    "configure_logging",
    "get_logger",
    "ANALYTICS_CONFIG",
    "ANALYSIS_DEFAULTS",
    "BOARD_HIDE_OBSOLETE",
    "BOARD_MIN_RECENT_VIEW",
    "RELEVANCE_WEIGHTS",
    "STRONG_ALIAS_LEN",
    "RELEVANCE_THRESHOLD",
    "HOTNESS_WEIGHTS",
    "HOTNESS_REFERENCE",
    "GROWTH_SCORE_FULL",
    "GROWTH_SCORE_ZERO",
    "MIN_SAMPLE_VIDEOS",
    "MIN_GROWTH_DISCUSSION",
    "LOW_SAMPLE_DAMPING",
    "LIFECYCLE_STAGES",
    "LIFECYCLE_LABELS",
    "LIFECYCLE_EMOJI",
    "LIFECYCLE_THRESHOLDS",
    "CATCHUP_THRESHOLDS",
    "CATCHUP_LABELS",
    "CATCHUP_EMOJI",
    "HOME_FILTERS",
    "HOME_FILTER_LABELS",
    # 分类体系（主题标签 + 算法专题）
    "TagSpec",
    "CollectionSpec",
    "MEME_TAGS",
    "TAG_KEYS",
    "TAG_LABELS",
    "TAG_EMOJI",
    "TAG_HINTS",
    "FALLBACK_TAG",
    "MAX_TAGS_PER_MEME",
    "COLLECTIONS",
    "COLLECTION_KEYS",
    "YEARLY_TOP_N",
]
